import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'

import "../styles/globals.css";

const montserrat = Montserrat({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
